package pe.edu.utp.tutor.config;

import java.math.BigDecimal;
import java.util.List;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.CommandLineRunner;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;
import pe.edu.utp.tutor.domain.*;
import pe.edu.utp.tutor.repository.*;
import pe.edu.utp.tutor.service.NotificationService;

@Component
public class DemoDataInitializer implements CommandLineRunner {
    private final boolean enabled; private final RoleRepository roles;private final UserRepository users;private final StudentRepository students;private final TeacherRepository teachers;
    private final ClassroomRepository classrooms;private final EnrollmentRepository enrollments;private final TopicRepository topics;private final ProgressRepository progress;private final AlertRepository alerts;private final NotificationRepository notifications;private final PasswordEncoder encoder;private final NotificationService notificationService;
    public DemoDataInitializer(@Value("${app.demo-data:true}")boolean enabled,RoleRepository roles,UserRepository users,StudentRepository students,TeacherRepository teachers,ClassroomRepository classrooms,EnrollmentRepository enrollments,TopicRepository topics,ProgressRepository progress,AlertRepository alerts,NotificationRepository notifications,PasswordEncoder encoder,NotificationService notificationService){this.enabled=enabled;this.roles=roles;this.users=users;this.students=students;this.teachers=teachers;this.classrooms=classrooms;this.enrollments=enrollments;this.topics=topics;this.progress=progress;this.alerts=alerts;this.notifications=notifications;this.encoder=encoder;this.notificationService=notificationService;}
    @Override @Transactional public void run(String...args){if(!enabled)return;RoleEntity sr=roles.findByName("STUDENT").orElseThrow(),tr=roles.findByName("TEACHER").orElseThrow();TeacherEntity teacher=teacher(tr);List<StudentEntity> roster=List.of(student(sr,"Ana Torres","alumno@demo.pe",1,"A"),student(sr,"Luis Ramos","luis@demo.pe",2,"B"),student(sr,"Marco Salas","marco@demo.pe",3,"A"),student(sr,"Rosa Díaz","rosa@demo.pe",4,"C"));for(StudentEntity s:roster)enroll(teacher,s);seedProgress(roster);}
    private TeacherEntity teacher(RoleEntity role){return teachers.findByUserEmailIgnoreCase("docente@demo.pe").orElseGet(()->{UserEntity u=user(role,"Prof. Carlos Medina","docente@demo.pe");TeacherEntity t=new TeacherEntity();t.setUser(u);t.setSpecialty("Matemática y Comunicación");return teachers.save(t);});}
    private StudentEntity student(RoleEntity role,String name,String email,int grade,String section){return students.findByUserEmailIgnoreCase(email).orElseGet(()->{UserEntity u=user(role,name,email);StudentEntity s=new StudentEntity();s.setUser(u);s.setGrade(grade);s.setSection(section);return students.save(s);});}
    private UserEntity user(RoleEntity role,String name,String email){return users.findByEmailIgnoreCase(email).orElseGet(()->{UserEntity u=new UserEntity();u.setRole(role);u.setFullName(name);u.setEmail(email);u.setPasswordHash(encoder.encode("1234"));return users.save(u);});}
    private void enroll(TeacherEntity t,StudentEntity s){ClassroomEntity c=classrooms.findAll().stream().filter(x->x.getTeacher().getId().equals(t.getId())&&x.getGrade()==s.getGrade()&&x.getSection().equals(s.getSection())).findFirst().orElseGet(()->{ClassroomEntity x=new ClassroomEntity();x.setTeacher(t);x.setGrade(s.getGrade());x.setSection(s.getSection());x.setName(s.getGrade()+".° "+s.getSection());return classrooms.save(x);});if(!enrollments.existsByClassroomIdAndStudentId(c.getId(),s.getId())){EnrollmentEntity e=new EnrollmentEntity();e.setClassroom(c);e.setStudent(s);enrollments.save(e);}}
    private void seedProgress(List<StudentEntity> roster){TopicEntity algebra=topics.findByCode("MAT_ALG").orElseThrow(),reading=topics.findByCode("COM_COMP").orElseThrow();int[]scores={78,55,38,61};for(int i=0;i<roster.size();i++){StudentEntity s=roster.get(i);ProgressEntity p=progress.findByStudentIdAndTopicId(s.getId(),algebra.getId()).orElseGet(ProgressEntity::new);if(p.getId()==null){p.setStudent(s);p.setTopic(algebra);p.setTotalAttempts(10);p.setCorrectAttempts(scores[i]/10);p.setCurrentLevel(scores[i]<60?"basico":"intermedio");p.setRecommendedLevel(p.getCurrentLevel());p.setAverageTimeSeconds(BigDecimal.valueOf(72+i*9));p.setConsecutiveErrors(scores[i]<60?2:0);progress.save(p);}ProgressEntity r=progress.findByStudentIdAndTopicId(s.getId(),reading.getId()).orElseGet(ProgressEntity::new);if(r.getId()==null){r.setStudent(s);r.setTopic(reading);r.setTotalAttempts(7);r.setCorrectAttempts(Math.max(3,scores[i]/14));r.setCurrentLevel("intermedio");r.setRecommendedLevel("intermedio");r.setAverageTimeSeconds(BigDecimal.valueOf(65));progress.save(r);}if(scores[i]<60&&alerts.findByStudentIdOrderByCreatedAtDesc(s.getId()).isEmpty()){AlertEntity a=new AlertEntity();a.setStudent(s);a.setCourse(algebra.getCourse());a.setTopic(algebra);a.setAlertType("LOW_PERFORMANCE");a.setReason("Rendimiento de demostración de "+scores[i]+"% en Álgebra.");a.setRiskLevel(scores[i]<45?"HIGH":"MEDIUM");a.setPedagogicalRecommendation("Asignar refuerzo básico y revisar los dos últimos procedimientos.");alerts.save(a);if(notifications.count()==0||notifications.findAll().stream().noneMatch(n->n.getStudent().getId().equals(s.getId())))notificationService.create(s,algebra,null,a,"LOW_PERFORMANCE",a.getReason(),a.getRiskLevel());}}
    }
}
